# Generated by Django 5.0.8 on 2024-12-03 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor_id_input',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course_code_input',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student_id_input',
        ),
        migrations.AlterField(
            model_name='course',
            name='day_time',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_code'], name='courses_cou_course__897db7_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student_id'], name='courses_enr_student_c453e8_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course_code'], name='courses_enr_course__000bef_idx'),
        ),
    ]
