# Generated by Django 5.0.8 on 2024-10-22 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(blank=True, max_length=100)),
                ('teacher_id', models.CharField(blank=True, max_length=10)),
                ('teacher_name', models.CharField(blank=True, max_length=100)),
                ('students_data', models.JSONField(default=dict)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('semester', models.CharField(max_length=10)),
                ('status', models.JSONField(default=dict)),
            ],
        ),
    ]
