# Generated by Django 5.0.8 on 2024-12-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_records', '0004_alter_attendance_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='semester',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='course_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='instructor_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_name',
            field=models.CharField(max_length=255),
        ),
    ]
