# Generated by Django 5.0.8 on 2024-10-17 06:55

import courses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(help_text='Enter 3-4 uppercase letters followed by 3 digits (e.g., CSC101)', max_length=20, primary_key=True, serialize=False, unique=True, validators=[courses.models.validate_course_code])),
                ('course_name', models.CharField(max_length=255)),
                ('credit_hours', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('class_lab', models.CharField(help_text='Enter the lab number, CL- will be prefixed automatically.', max_length=10)),
                ('day_time', models.CharField(help_text="Enter the schedule (e.g., 'Mon & Wed 9-11 AM')", max_length=255)),
                ('instructor_id_input', models.CharField(help_text='Enter the Instructor custom ID', max_length=100)),
                ('instructor_full_name', models.CharField(editable=False, max_length=255)),
                ('semester', models.CharField(choices=[('Fall 2024', 'Fall 2024'), ('Spring 2024', 'Spring 2024'), ('Summer 2024', 'Summer 2024')], help_text="Choose from the current semesters (e.g., 'Fall 2024').", max_length=20, validators=[courses.models.validate_semester])),
                ('instructor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_input', models.CharField(help_text='Enter the Student custom ID', max_length=100)),
                ('course_name', models.CharField(editable=False, max_length=255)),
                ('credit_hours', models.PositiveIntegerField(editable=False)),
                ('class_lab', models.CharField(editable=False, max_length=10)),
                ('day_time', models.CharField(editable=False, max_length=255)),
                ('instructor_name', models.CharField(editable=False, max_length=255)),
                ('semester', models.CharField(editable=False, max_length=20)),
                ('student_name', models.CharField(editable=False, max_length=255)),
                ('course_code', models.ForeignKey(help_text='Select a course', on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
